services:
  flyfone-bot:
    build:
      context: ..              # ← one level up, where package.json lives
      dockerfile: Docker/Dockerfile
    env_file:
      - ./env
    restart: always
    volumes:
      - ./src/cookies.json:/usr/src/app/src/cookies.json
