FROM node:20-alpine

# set working dir
WORKDIR /usr/src/app

# copy package files & install
COPY package*.json ./
RUN npm install --production
# copy your source
COPY src ./src

# set workdir to src
WORKDIR /usr/src/app/src

# no EXPOSE needed for polling-only, but you can
EXPOSE 3000

# launch polling bot
CMD ["node", "bot.js"]
